# Generated by Django 4.2.3 on 2023-07-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CastoonnApp', '0002_alter_user_registration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_temp', models.EmailField(max_length=254, unique=True)),
                ('email_otp_temp', models.IntegerField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
