# Generated by Django 4.2.3 on 2023-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CastoonnApp', '0004_alter_email_validation_email_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='email_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
